package com.pichincha.cdemsaspopenaidocumentation.prompt.domain;

public enum PromptType {
  ERROR_MANUAL,
  API_DOCUMENTATION,
  ARCHITECTURE_DOCUMENTATION,
  README_GENERATION,
  CHANGELOG,
  CODE_DOCUMENTATION,
  TECHNICAL_SPECIFICATION,
  DEPLOYMENT_GUIDE
}